# Generated by Django 3.0.5 on 2020-04-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalImage', models.FileField(upload_to='')),
                ('imagePath', models.FilePathField()),
                ('originalNumberImage', models.FileField(upload_to='')),
                ('superResolutionNumberImage', models.FileField(upload_to='')),
                ('numberText', models.CharField(max_length=10)),
            ],
        ),
    ]
