# Generated by Django 3.0.5 on 2020-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carNumberRecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='imagePath',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='originalImage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='originalNumberImage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='superResolutionNumberImage',
            field=models.CharField(max_length=10),
        ),
    ]
