# Generated by Django 3.1.4 on 2021-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carNumberRecognition', '0002_auto_20200408_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Recognition',
        ),
    ]
